version: '3.7'

services:
    web-server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: example-web-server
        expose:
            - '8080'
        ports:
            - '8080:8080'
            - '9229:9229'
        command: npm start
