export const filterMapper = {
	id: 'id',
	title: 'title',
	name: 'title',
	vote_average: 'vote_average',
	vote_count: 'vote_count',
	status: 'status',
	year: 'release_date',
	revenue: 'revenue',
	runtime: 'runtime',
	adult: 'adult',
	budget: 'budget',
	imdb_id: 'imdb_id',
	og_language: 'original_language',
	og_title: 'original_title',
	popularity: 'popularity',
	genres: 'genres',
	production_companies: 'production_companies',
	production_countries: 'production_countries',
	languages: 'spoken_languages',
	keywords: 'keywords',
}
