ENV: 'dev'
PORT: '8080'
DB_MOVIE: 'magic_db'
DB_HOST: 'localhost'
DB_PORT: '5432'
DB_USER: 'postgres'
DB_PASSWORD: '1234secure&D3'
DB_MOVIES_TABLE: 'magic_movie_catalogue'
DB_MOVIE_USERS: 'magic_movie_users'
SIZE: '1000'
LOCAL: 'true'
